#!/bin/zsh

source ./lib/check_install.zsh
source ./lib/prun.zsh

prun check_install git zsh wget curl powerline autojump locales fzf zoxide

# gen en_US.UTF-8
prun sudo locale-gen en_US.UTF-8

# install .oh-my-zsh
if [ ! -d ${HOME}/.oh-my-zsh ]; then
    prun wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O /tmp/install.sh
    prun yes Y | sh /tmp/install.sh
fi

# install zsh-syntax-highlight
if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting ]; then
    prun git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

# install zsh-autosuggestions
if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions ]; then
    prun git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi

# install p10k theme
if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k ]; then
    prun git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi

# install zunit for testing
if ! command -v zunit &>/dev/null; then
  prun git clone --depth=1 https://github.com/molovo/revolver /tmp/revolver-install
  prun sudo install /tmp/revolver-install/revolver /usr/local/bin/revolver
  rm -rf /tmp/revolver-install
  prun git clone --depth=1 https://github.com/zunit-zsh/zunit.git /tmp/zunit-install
  (cd /tmp/zunit-install && prun zsh build.zsh)
  prun sudo install /tmp/zunit-install/zunit /usr/local/bin/zunit
  rm -rf /tmp/zunit-install
fi

# Generate a fresh ~/.zshrc that sources the repo's zsh/.zshrc {{{
git_root_path=$(git rev-parse --show-toplevel)
repo_zshrc="$git_root_path/zsh/.zshrc"
zlib_path="$git_root_path/zsh/lib"

# Remove any existing ~/.zshrc first. It may be a symlink to the repo's
# zsh/.zshrc (from an older install); writing through it would clobber the
# tracked file, so unlink it before generating a fresh regular file.
rm -f ~/.zshrc

cat > ~/.zshrc <<EOF
# This file is generated by ubuntu-settings zsh/install.sh.
# Do not edit it directly; edit $repo_zshrc instead.
export ZSH_LIB_PATH="$zlib_path"
source "$repo_zshrc"
EOF

printf "Generated ~/.zshrc:\n"
printf "  ZSH_LIB_PATH: $zlib_path\n"
printf "  source:       $repo_zshrc\n"
# }}} Generate ~/.zshrc

if [[ -z "$CI" ]]; then
  prun sudo chsh -s $(which zsh)
fi
