#!/bin/zsh

# Remove the generated ~/.zshrc created by install.sh.
if [ -f ~/.zshrc ] && grep -q "generated by ubuntu-settings" ~/.zshrc; then
  echo "Removing generated ~/.zshrc"
  rm -f ~/.zshrc
else
  echo "~/.zshrc was not generated by ubuntu-settings; leaving it untouched."
fi

# Clean up legacy symlinks from older installs, if present.
[ -L ~/.zsh/zlib ] && rm -f ~/.zsh/zlib
[ -L ~/.zsh/zlib.zsh ] && rm -f ~/.zsh/zlib.zsh
